sonar.projectKey=ChristianDGF_Sistema-Gestion-FST-O-DSO
sonar.organization=christiandgf
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.java.source=21
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/dto/**, **/entity/**, **/enums/**, **/SistemaGestionApplication.java
sonar.cpd.exclusions=**/dto/**, **/entity/**
