-- Hibernate Envers audit tables
-- These are auto-generated by Hibernate Envers, but we create them explicitly
-- for Flyway migration management

CREATE TABLE IF NOT EXISTS products_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    name VARCHAR(255),
    sku VARCHAR(255),
    description TEXT,
    category VARCHAR(255),
    price DECIMAL(10, 2),
    quantity INTEGER,
    min_stock INTEGER,
    status VARCHAR(20),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS stock_movements_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    product_id BIGINT,
    movement_type VARCHAR(20),
    quantity INTEGER,
    previous_quantity INTEGER,
    new_quantity INTEGER,
    user_id VARCHAR(255),
    observations TEXT,
    created_at TIMESTAMP,
    PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS revinfo (
    rev SERIAL PRIMARY KEY,
    revtstmp BIGINT
);
